version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: app/backend
    container_name: backend
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=shoot
      - DB_PASSWORD=leo24
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - app-network
#    extra_hosts:
#      - host.docker.internal:host-gateway

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app/backend
      - ./backend/docker/nginx/:/etc/nginx/conf.d/
    depends_on:
      - db
      - backend
    links:
      - backend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - "3000:3000"
#    volumes:
#      - ./frontend:/app/frontend
#      - ./frontend:/app/frontend/node_modules
    links:
      - backend
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'shoot'
      MYSQL_PASSWORD: 'leo24'
      MYSQL_ROOT_PASSWORD: 'chyortpoberr90i'
    networks:
      - app-network

  adminer:
    image: adminer
    ports:
      - "${ADMINER_PORT:-8080}:8080"
    depends_on:
      - db
    environment:
      - ADMINER_DEFAULT_SERVER=db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge